from pathlib import Path

shell = Path('static/js/skillui-shell.js')
s = shell.read_text()
old = '''function bindGid() {\n  const input = VIEWPORT.querySelector('#code');\n  VIEWPORT.querySelector('#auth')?.addEventListener('click', async () => {\n    try {\n      await Mercury.authenticate(input?.value || '');\n      Mercury.toast('GID authenticated.');\n      setTimeout(() => navigate('/home/'), 320);\n    } catch (error) {\n      Mercury.toast(error.message);\n    }\n  });\n  VIEWPORT.querySelector('#public')?.addEventListener('click', () => navigate('/home/?demo=1'));\n}\n'''
new = '''function bindGid() {\n  const email = VIEWPORT.querySelector('#email');\n  const display = VIEWPORT.querySelector('#display');\n  const password = VIEWPORT.querySelector('#password');\n  const state = VIEWPORT.querySelector('#member-state');\n  const ownerCode = VIEWPORT.querySelector('#code');\n  const show = message => {\n    if (state) state.textContent = message;\n    Mercury.toast(message);\n  };\n\n  VIEWPORT.querySelector('#signup')?.addEventListener('click', async () => {\n    try {\n      if (state) state.textContent = 'Creating your Galactic Identity…';\n      const result = await Mercury.auth.signup({\n        email: email?.value || '',\n        password: password?.value || '',\n        display_name: display?.value || ''\n      });\n      if (result?.confirmation_required) {\n        show('GID created. Confirm your email, then sign in.');\n        return;\n      }\n      await Mercury.identity();\n      show('GID active · Free tier. Welcome home.');\n      setTimeout(() => navigate('/home/'), 320);\n    } catch (error) {\n      show(error.message);\n    }\n  });\n\n  VIEWPORT.querySelector('#login')?.addEventListener('click', async () => {\n    try {\n      if (state) state.textContent = 'Restoring your identity…';\n      await Mercury.auth.login({ email: email?.value || '', password: password?.value || '' });\n      await Mercury.identity();\n      show('Identity restored. Welcome home.');\n      setTimeout(() => navigate('/home/'), 320);\n    } catch (error) {\n      show(error.message);\n    }\n  });\n\n  VIEWPORT.querySelector('#auth')?.addEventListener('click', async () => {\n    try {\n      await Mercury.authenticate(ownerCode?.value || '');\n      show('Prime Orchestrator authenticated.');\n      setTimeout(() => navigate('/home/'), 320);\n    } catch (error) {\n      show(error.message);\n    }\n  });\n  VIEWPORT.querySelector('#public')?.addEventListener('click', () => navigate('/home/?demo=1'));\n}\n'''
if old not in s:
    raise SystemExit('bindGid source contract not found')
s = s.replace(old, new, 1)
shell.write_text(s)

runtime = Path('static/js/runtime.js')
r = runtime.read_text()
needle = '''  async function billingPortal({ redirect = true } = {}) {\n    const result = await request(CONFIG.routes.billingPortal, { method: 'POST', body: {} });\n    if (redirect && result?.url) location.assign(result.url);\n    return result;\n  }\n\n'''
insert = needle + '''  async function confirmBillingReturn({ attempts = 12, delay = 850 } = {}) {\n    const params = new URLSearchParams(location.search);\n    const checkoutState = params.get('checkout');\n    const portalState = params.get('billing');\n\n    if (checkoutState === 'cancel') {\n      toast('Checkout canceled. Your current access is unchanged.');\n      return null;\n    }\n\n    if (portalState === 'return' && state.accessToken) {\n      const current = await billingStatus();\n      toast(`Membership · ${current?.tier || 'free'}`);\n      return current;\n    }\n\n    if (checkoutState !== 'return' || !state.accessToken) return null;\n\n    toast('Confirming membership…');\n    let current = null;\n    for (let attempt = 0; attempt < attempts; attempt += 1) {\n      current = await billingStatus();\n      if (['beta', 'alpha', 'owner'].includes(current?.tier) && ['active', 'trialing'].includes(current?.status)) {\n        toast(`Membership confirmed · ${current.tier}`);\n        return current;\n      }\n      await sleep(delay);\n    }\n    toast('Payment received. Membership is still being confirmed.');\n    return current;\n  }\n\n'''
if needle not in r:
    raise SystemExit('billingPortal source contract not found')
r = r.replace(needle, insert, 1)
r = r.replace("      portal: billingPortal\n", "      portal: billingPortal,\n      confirmReturn: confirmBillingReturn\n", 1)
r = r.replace("  };\n})();\n", "  };\n\n  queueMicrotask(() => confirmBillingReturn().catch(() => {}));\n})();\n", 1)
runtime.write_text(r)
